/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFiles;

import static MainFiles.IndexPage.userUnites;
import db.ConnectSql;
import functions.ValidateFields;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ravindu
 */
public class UserUnites extends javax.swing.JInternalFrame {

    private final String select = "--Select--";
    private final DefaultTableModel model_categoryTable;
    private final String spliter = "--";
    private final String menuName = "User units";

    /**
     * Creates new form Department
     */
    public UserUnites() {
        initComponents();

        buttonGroup1.add(rBtnCode);
        buttonGroup1.add(rBtnName);
        rBtnCode.setSelected(true);
        txtCode.requestFocus();
        model_categoryTable = (DefaultTableModel) TableCategory.getModel();
        panel1.setToolTipText("Press right mouse click to refresh.");

        LoadCategories();
        loadBaseSiUnitToCombo();
        loadTypes();
    }

    private void LoadCategories() {
        try {
            ResultSet reset;
            Statement stmt;
            String query;
            int rowCount = 0;
            query = "SELECT * FROM SIUnits ORDER BY UnitName";
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            while (reset.next()) {
                model_categoryTable.addRow(new Object[model_categoryTable.getColumnCount()]);
                TableCategory.setValueAt(reset.getString("UnitCode"), rowCount, 0);
                TableCategory.setValueAt(reset.getString("UnitName"), rowCount, 1);
                TableCategory.setValueAt(reset.getString("PurchaseMeasurement"), rowCount, 2);
                TableCategory.setValueAt(reset.getString("IssueMeasurement"), rowCount, 3);
                rowCount++;
            }
            reset.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void loadBaseSiUnitToCombo() {
        try {
            java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "select BaseUnitCode From SIUnitsBase order by BaseUnitCode";
            ResultSet rset = stmt.executeQuery(query);

            cmbBaseSiUnit.removeAllItems();
            cmbBaseSiUnit.insertItemAt("--Select--", 0);
            int position = 1;
            if (rset.next()) {
                do {
                    cmbBaseSiUnit.insertItemAt(rset.getString("BaseUnitCode"), position);
                    position++;
                } while (rset.next());
            }
            cmbBaseSiUnit.setSelectedIndex(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", ERROR);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        lbl_category = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtCategoryName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lbl_description = new javax.swing.JLabel();
        lbl_subAccount = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        rBtnCode = new javax.swing.JRadioButton();
        rBtnName = new javax.swing.JRadioButton();
        lbl_accountType = new javax.swing.JLabel();
        cmbTypes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCategory = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cmbBaseSiUnit = new javax.swing.JComboBox();
        lbl_accountType1 = new javax.swing.JLabel();
        FormattedTextPurchaseMeasurement = new javax.swing.JFormattedTextField();
        lbl_accountType2 = new javax.swing.JLabel();
        textRemarks = new javax.swing.JTextField();
        lbl_accountType3 = new javax.swing.JLabel();
        FormattedTextIssueMeasurement = new javax.swing.JFormattedTextField();

        setIconifiable(true);
        setTitle("User Unites");
        setPreferredSize(new java.awt.Dimension(895, 422));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
        });
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_category.setForeground(new java.awt.Color(102, 102, 102));
        lbl_category.setText("Unit code");
        panel1.add(lbl_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 110, 20));

        txtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodeFocusGained(evt);
            }
        });
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodeKeyReleased(evt);
            }
        });
        panel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 170, 20));

        txtCategoryName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCategoryNameFocusGained(evt);
            }
        });
        txtCategoryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCategoryNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoryNameKeyReleased(evt);
            }
        });
        panel1.add(txtCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 210, 20));

        btnSave.setMnemonic('s');
        btnSave.setText("Save");
        btnSave.setActionCommand("Delete");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 80, -1));

        btnDelete.setMnemonic('d');
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 80, -1));

        lbl_description.setForeground(new java.awt.Color(102, 102, 102));
        lbl_description.setText("Unit name");
        panel1.add(lbl_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 110, 20));

        lbl_subAccount.setForeground(new java.awt.Color(102, 102, 102));
        lbl_subAccount.setText("Search unites by");
        panel1.add(lbl_subAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 20));

        btnExit.setMnemonic('e');
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExitKeyPressed(evt);
            }
        });
        panel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 80, -1));

        rBtnCode.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnCode);
        rBtnCode.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rBtnCode.setText("Code");
        rBtnCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnCodeActionPerformed(evt);
            }
        });
        panel1.add(rBtnCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 60, -1));

        rBtnName.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnName);
        rBtnName.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rBtnName.setText("Name");
        rBtnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnNameActionPerformed(evt);
            }
        });
        rBtnName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rBtnNameKeyPressed(evt);
            }
        });
        panel1.add(rBtnName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 60, -1));

        lbl_accountType.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType.setText("Remarks");
        panel1.add(lbl_accountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 110, 20));

        cmbTypes.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbTypesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbTypes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbTypesKeyPressed(evt);
            }
        });
        panel1.add(cmbTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 210, 20));

        TableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Pur. Measure", "Issue. Measure"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCategory.getTableHeader().setReorderingAllowed(false);
        TableCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCategory);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 310));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        panel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 170, -1));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 350, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Base SI unit");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 114, 20));

        cmbBaseSiUnit.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbBaseSiUnitPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbBaseSiUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbBaseSiUnitKeyPressed(evt);
            }
        });
        panel1.add(cmbBaseSiUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 210, 20));

        lbl_accountType1.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType1.setText("Unit Type");
        panel1.add(lbl_accountType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, 20));

        FormattedTextPurchaseMeasurement.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FormattedTextPurchaseMeasurement.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FormattedTextPurchaseMeasurement.setText("1");
        FormattedTextPurchaseMeasurement.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FormattedTextPurchaseMeasurementFocusGained(evt);
            }
        });
        FormattedTextPurchaseMeasurement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FormattedTextPurchaseMeasurementKeyPressed(evt);
            }
        });
        panel1.add(FormattedTextPurchaseMeasurement, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 170, -1));

        lbl_accountType2.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType2.setText("Issue Measurement");
        panel1.add(lbl_accountType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, 20));

        textRemarks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textRemarksFocusGained(evt);
            }
        });
        textRemarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textRemarksKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textRemarksKeyReleased(evt);
            }
        });
        panel1.add(textRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 210, -1));

        lbl_accountType3.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType3.setText("Purchase Measurement");
        panel1.add(lbl_accountType3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 120, 20));

        FormattedTextIssueMeasurement.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FormattedTextIssueMeasurement.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FormattedTextIssueMeasurement.setText("1");
        FormattedTextIssueMeasurement.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FormattedTextIssueMeasurementFocusGained(evt);
            }
        });
        FormattedTextIssueMeasurement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FormattedTextIssueMeasurementKeyPressed(evt);
            }
        });
        panel1.add(FormattedTextIssueMeasurement, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodeFocusGained
        txtCode.selectAll();
    }//GEN-LAST:event_txtCodeFocusGained

    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String text = txtCode.getText();
            if (!text.isEmpty()) {
                txtCategoryName.requestFocus();
                LoadAtCodes();
            }
        }
    }//GEN-LAST:event_txtCodeKeyPressed

    private void LoadAtCodes() {
        String CategoryCode = txtCode.getText();
        try {
            ResultSet reset;
            Statement stmt;
            String query;
            query = "SELECT * FROM SIUnits where UnitCode = '" + CategoryCode + "'";
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            if (reset.next()) {
                txtCategoryName.setText(reset.getString("DepartmentName"));
                FormattedTextPurchaseMeasurement.setText(reset.getString("PurchaseMeasurement"));
                FormattedTextIssueMeasurement.setText(reset.getString("IssueMeasurement"));
                cmbBaseSiUnit.setSelectedItem(reset.getString("BaseUnitCode"));
                cmbTypes.setSelectedItem(reset.getString("UnitType"));
                textRemarks.setText(reset.getString("Remarks"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void txtCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyReleased
        ValidateFields.CheckForCodes(txtCode);
    }//GEN-LAST:event_txtCodeKeyReleased

    private void txtCategoryNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCategoryNameFocusGained
        txtCategoryName.selectAll();
    }//GEN-LAST:event_txtCategoryNameFocusGained

    private void txtCategoryNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoryNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String text = txtCategoryName.getText();
            if (!text.isEmpty()) {
                cmbBaseSiUnit.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCategoryNameKeyPressed

    private void txtCategoryNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoryNameKeyReleased
        ValidateFields.CheckForOtherFields(txtCategoryName);
    }//GEN-LAST:event_txtCategoryNameKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        CheckBeforeSave();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void CheckBeforeSave() {
        String CategoryCode = txtCode.getText();
        String CategoryName = txtCategoryName.getText();
        String BaseUnitID = cmbBaseSiUnit.getSelectedItem().toString();
        String Type = cmbTypes.getSelectedItem().toString();
        String remarks = textRemarks.getText();
        String purchaseMeasurement = FormattedTextPurchaseMeasurement.getText();
        String issueMeasurement = FormattedTextIssueMeasurement.getText();
        if (!CategoryCode.isEmpty() && !CategoryName.isEmpty() && !Type.equals(select)
                && !BaseUnitID.equals(select) && !purchaseMeasurement.isEmpty() && !issueMeasurement.isEmpty()) {
            try {
                java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String query = "select UnitCode From SIUnits where UnitCode = '" + CategoryCode + "'";
                ResultSet rset = stmt.executeQuery(query);

                if (rset.next()) {
                    int x = JOptionPane.showConfirmDialog(this, "Are you sure to change the '" + CategoryCode + "' " + menuName + " details?", "Update '" + menuName + "'?", JOptionPane.YES_NO_OPTION);
                    if (x == JOptionPane.YES_OPTION) {
                        String UpdateQuery = "UPDATE [SIUnits]\n"
                                + "   SET [UnitName] = '" + CategoryName + "'\n"
                                + "      ,[PurchaseMeasurement] = '" + purchaseMeasurement + "'\n"
                                + "      ,[IssueMeasurement] = '" + issueMeasurement + "'\n"
                                + "      ,[Remarks] = '" + remarks + "'\n"
                                + "      ,[BaseUnitCode] = '" + BaseUnitID + "'\n"
                                + "      ,[UnitType] = '" + Type + "'\n"
                                + " WHERE [UnitCode] = '" + CategoryCode + "'";
                        stmt.execute(UpdateQuery);
                        JOptionPane.showMessageDialog(this, "'" + menuName + "' details are updated.");
                        Refresh();
                    } else if (x == JOptionPane.NO_OPTION) {
                        txtCode.requestFocus();
                    }

                } else if (!rset.next()) {
                    String UpdateQuery = "INSERT INTO [SIUnits]\n"
                            + "           ([UnitCode]\n"
                            + "           ,[UnitName]\n"
                            + "           ,[PurchaseMeasurement]\n"
                            + "           ,[IssueMeasurement]\n"
                            + "           ,[Remarks]\n"
                            + "           ,[BaseUnitCode]\n"
                            + "           ,[UnitType])\n"
                            + "     VALUES\n"
                            + "           ('" + CategoryCode + "'\n"
                            + "           ,'" + CategoryName + "'\n"
                            + "           ,'" + purchaseMeasurement + "'\n"
                            + "           ,'" + issueMeasurement + "'\n"
                            + "           ,'" + remarks + "'\n"
                            + "           ,'" + BaseUnitID + "'\n"
                            + "           ,'" + Type + "')";
                    stmt.execute(UpdateQuery);
                    JOptionPane.showMessageDialog(this, "New '" + menuName + "' is saved.");
                    Refresh();
                }
                rset.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            }
        } else if (CategoryCode.isEmpty() || CategoryName.isEmpty() || Type.equals(select)) {
            JOptionPane.showMessageDialog(this, "Please fill all fields before save.", "Empty fields", JOptionPane.OK_OPTION);
            txtCode.requestFocus();
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        CheckBeforeDelete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void CheckBeforeDelete() {
        String CategoryCode = txtCode.getText();
        if (!CategoryCode.isEmpty()) {
            try {
                java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String query = "select UnitPurchase From Items where UnitPurchase = '" + CategoryCode + "'";
                ResultSet rset = stmt.executeQuery(query);

                if (rset.next()) {
                    JOptionPane.showMessageDialog(this, "This unit is already used. Can't delete.", "Can't delete", JOptionPane.ERROR_MESSAGE);
                } else if (!rset.next()) {
                    DeleteDepartment();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            }
        } else if (CategoryCode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a valid unit code before delete.", "Empty unit code", JOptionPane.OK_OPTION);
            txtCode.requestFocus();
        }
    }

    private void DeleteDepartment() {
        String Code = txtCode.getText();
        int x = JOptionPane.showConfirmDialog(this, "Are you sure To delete this?", "Delete unit?", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            try {
                java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                java.sql.Statement Checkstmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

                String Checkquery = "select DepartmentCode From Departments where DepartmentCode = '" + Code + "'";
                ResultSet Checkrset = Checkstmt.executeQuery(Checkquery);

                if (Checkrset.next()) {
                    String query = "delete From Departments where DepartmentCode = '" + Code + "'";
                    stmt.execute(query);
                    JOptionPane.showMessageDialog(this, "unit is deleted.");
                    Refresh();
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid unit code. Please insert a valid unit code.", "Invalid unit code", JOptionPane.OK_OPTION);
                    txtCode.requestFocus();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            }

        } else if (x == JOptionPane.NO_OPTION) {
            txtCode.requestFocus();
        }
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            exit();
        }
    }//GEN-LAST:event_btnExitKeyPressed

    private void rBtnCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnCodeActionPerformed
        if (rBtnCode.isSelected()) {
            txtSearch.requestFocus();
            txtSearch.selectAll();
        }
    }//GEN-LAST:event_rBtnCodeActionPerformed

    private void rBtnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnNameActionPerformed
        if (rBtnName.isSelected()) {
            txtSearch.requestFocus();
            txtSearch.selectAll();
        }
    }//GEN-LAST:event_rBtnNameActionPerformed

    private void rBtnNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rBtnNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            rBtnCode.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rBtnName.setSelected(true);
            btnSave.requestFocus();
        }
    }//GEN-LAST:event_rBtnNameKeyPressed

    private void cmbTypesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbTypesPopupMenuWillBecomeInvisible
        String text = cmbTypes.getSelectedItem().toString();
        if (!text.equals(select)) {
            FormattedTextPurchaseMeasurement.requestFocus();
        }
    }//GEN-LAST:event_cmbTypesPopupMenuWillBecomeInvisible

    private void cmbTypesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbTypesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String text = cmbTypes.getSelectedItem().toString();
            if (!text.equals(select)) {
                FormattedTextPurchaseMeasurement.requestFocus();
            }
        }
    }//GEN-LAST:event_cmbTypesKeyPressed

    private void TableCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCategoryMouseClicked
        String Code, Name, purchaseMeasurement, issueMeasurement, BaseUnitCode = "", remarks = "", UnitType = "";

        Code = TableCategory.getValueAt(TableCategory.getSelectedRow(), 0).toString();
        Name = TableCategory.getValueAt(TableCategory.getSelectedRow(), 1).toString();
        purchaseMeasurement = TableCategory.getValueAt(TableCategory.getSelectedRow(), 2).toString();
        issueMeasurement = TableCategory.getValueAt(TableCategory.getSelectedRow(), 3).toString();

        try {
            ResultSet reset;
            Statement stmt;
            String query;
            query = "SELECT [UnitCode]\n"
                    + "      ,[UnitName]\n"
                    + "      ,[PurchaseMeasurement]\n"
                    + "      ,[IssueMeasurement]\n"
                    + "      ,[Remarks]\n"
                    + "      ,[BaseUnitCode]\n"
                    + "      ,[UnitType]\n"
                    + "  FROM [SIUnits] where UnitCode = '" + Code + "'";
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            if (reset.next()) {
                remarks = reset.getString("Remarks");
                BaseUnitCode = reset.getString("BaseUnitCode");
                UnitType = reset.getString("UnitType");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }

        txtCode.setText(Code);
        txtCategoryName.setText(Name);
        FormattedTextPurchaseMeasurement.setText(purchaseMeasurement);
        FormattedTextIssueMeasurement.setText(issueMeasurement);
        cmbBaseSiUnit.setSelectedItem(BaseUnitCode);
        cmbTypes.setSelectedItem(UnitType);
        textRemarks.setText(remarks);
        txtCategoryName.requestFocus();
    }//GEN-LAST:event_TableCategoryMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        if (rBtnCode.isSelected()) {
            SearchCategoryByCode(txtSearch.getText());
        } else if (rBtnName.isSelected()) {
            SearchCategoryByName(txtSearch.getText());
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void SearchCategoryByCode(String CategoryCode) {
        try {
            ResultSet reset;
            Statement stmt;
            String query;
            int rowCount = 0;
            RefreshTable();

            if (!CategoryCode.equals("")) {
                query = "SELECT * FROM SIUnits WHERE UnitCode LIKE '" + CategoryCode + "%'";
            } else {
                query = "SELECT * FROM SIUnits  WHERE UnitCode LIKE '" + CategoryCode + "%'";
            }
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            while (reset.next()) {

                model_categoryTable.addRow(new Object[model_categoryTable.getColumnCount()]);
                TableCategory.setValueAt(reset.getString("UnitCode"), rowCount, 0);
                TableCategory.setValueAt(reset.getString("UnitName"), rowCount, 1);
                TableCategory.setValueAt(reset.getString("PurchaseMeasurement"), rowCount, 2);
                TableCategory.setValueAt(reset.getString("IssueMeasurement"), rowCount, 3);
                rowCount++;
            }
            reset.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void SearchCategoryByName(String CategoryName) {
        try {
            ResultSet reset;
            Statement stmt;
            String query;
            int rowCount = 0;
            RefreshTable();

            if (!CategoryName.equals("")) {
                query = "SELECT * FROM SIUnits WHERE UnitName LIKE '%" + CategoryName + "%'";
            } else {
                query = "SELECT * FROM SIUnits WHERE UnitName LIKE '%" + CategoryName + "%'";
            }
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            while (reset.next()) {

                model_categoryTable.addRow(new Object[model_categoryTable.getColumnCount()]);
                TableCategory.setValueAt(reset.getString("UnitCode"), rowCount, 0);
                TableCategory.setValueAt(reset.getString("UnitName"), rowCount, 1);
                TableCategory.setValueAt(reset.getString("PurchaseMeasurement"), rowCount, 2);
                TableCategory.setValueAt(reset.getString("IssueMeasurement"), rowCount, 3);
                rowCount++;
            }
            reset.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void RefreshTable() {
        try {
            int row = model_categoryTable.getRowCount();
            for (int j = 0; j < row; j++) {
                model_categoryTable.removeRow(0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseClicked
        if (SwingUtilities.isRightMouseButton(evt) || evt.isControlDown()) {
            Refresh();
        }
    }//GEN-LAST:event_panel1MouseClicked

    private void cmbBaseSiUnitPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbBaseSiUnitPopupMenuWillBecomeInvisible
        if (cmbBaseSiUnit.getSelectedItem().equals(select)) {
            cmbBaseSiUnit.requestFocus();
        } else {
            cmbTypes.requestFocus();
        }
    }//GEN-LAST:event_cmbBaseSiUnitPopupMenuWillBecomeInvisible

    private void cmbBaseSiUnitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbBaseSiUnitKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cmbBaseSiUnit.getSelectedItem().equals(select)) {
                cmbBaseSiUnit.requestFocus();
            } else {
                cmbTypes.requestFocus();
            }
        }
    }//GEN-LAST:event_cmbBaseSiUnitKeyPressed

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        userUnites.toFront();
    }//GEN-LAST:event_formInternalFrameIconified

    private void FormattedTextPurchaseMeasurementKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FormattedTextPurchaseMeasurementKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String text = FormattedTextPurchaseMeasurement.getText();
            if (!text.equals("")) {
                FormattedTextIssueMeasurement.requestFocus();
            }
        }
    }//GEN-LAST:event_FormattedTextPurchaseMeasurementKeyPressed

    private void textRemarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textRemarksKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSave.requestFocus();
        }
    }//GEN-LAST:event_textRemarksKeyPressed

    private void textRemarksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textRemarksKeyReleased
        ValidateFields.CheckForOtherFields(textRemarks);
    }//GEN-LAST:event_textRemarksKeyReleased

    private void FormattedTextIssueMeasurementKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FormattedTextIssueMeasurementKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String text = FormattedTextIssueMeasurement.getText();
            if (!text.equals("")) {
                textRemarks.requestFocus();
            }
        }
    }//GEN-LAST:event_FormattedTextIssueMeasurementKeyPressed

    private void FormattedTextPurchaseMeasurementFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FormattedTextPurchaseMeasurementFocusGained
        FormattedTextPurchaseMeasurement.selectAll();
    }//GEN-LAST:event_FormattedTextPurchaseMeasurementFocusGained

    private void FormattedTextIssueMeasurementFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FormattedTextIssueMeasurementFocusGained
        FormattedTextIssueMeasurement.selectAll();
    }//GEN-LAST:event_FormattedTextIssueMeasurementFocusGained

    private void textRemarksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRemarksFocusGained
        textRemarks.selectAll();
    }//GEN-LAST:event_textRemarksFocusGained

    private void Refresh() {
        RefreshTableAndLoadAgain();
        txtCode.setText("");
        txtCategoryName.setText("");
        cmbTypes.setSelectedIndex(0);
        txtSearch.setText("");
        FormattedTextPurchaseMeasurement.setText("1.0");
        FormattedTextIssueMeasurement.setText("1.0");
        textRemarks.setText("");
    }

    private void RefreshTableAndLoadAgain() {
        try {
            int row = model_categoryTable.getRowCount();
            for (int j = 0; j < row; j++) {
                model_categoryTable.removeRow(0);
            }
            LoadCategories();
            loadBaseSiUnitToCombo();
            loadTypes();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FormattedTextIssueMeasurement;
    private javax.swing.JFormattedTextField FormattedTextPurchaseMeasurement;
    private javax.swing.JTable TableCategory;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbBaseSiUnit;
    private javax.swing.JComboBox cmbTypes;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_accountType;
    private javax.swing.JLabel lbl_accountType1;
    private javax.swing.JLabel lbl_accountType2;
    private javax.swing.JLabel lbl_accountType3;
    private javax.swing.JLabel lbl_category;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_subAccount;
    private javax.swing.JPanel panel1;
    private javax.swing.JRadioButton rBtnCode;
    private javax.swing.JRadioButton rBtnName;
    private javax.swing.JTextField textRemarks;
    private javax.swing.JTextField txtCategoryName;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void exit() {
        if (userUnites != null) {
            userUnites = null;
        }
        this.dispose();
    }

    private void loadTypes() {
        try {
            java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "select TypeCode, TypeName From ItemTypes order by TypeName";
            ResultSet rset = stmt.executeQuery(query);

            cmbTypes.removeAllItems();
            cmbTypes.insertItemAt("--Select--", 0);
            int position = 1;
            if (rset.next()) {
                do {
                    cmbTypes.insertItemAt(rset.getString("TypeName"), position); // + "--" + rset.getString("TypeCode")
                    position++;
                } while (rset.next());
            }
            cmbTypes.setSelectedIndex(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", ERROR);
        }
    }

}
